Controllers/EnumUrlSegmentAdminController.cs
using MainBit.Alias.Helpers;
using MainBit.Alias.Models;
using MainBit.Alias.Services;
using MainBit.Alias.ViewModels;
using Orchard;
using Orchard.Caching;
using Orchard.ContentManagement;
using Orchard.Localization;
using Orchard.Security;
using Orchard.UI.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MainBit.Alias.Controllers
{
    [Admin]
    public class EnumUrlSegmentAdminController : Controller, IUpdateModel
    {
        private readonly IEnumUrlSegmentRepository _enumUrlSegmentService;
        private readonly IOrchardServices _orchardServices;

        public EnumUrlSegmentAdminController(
            IEnumUrlSegmentRepository enumUrlSegmentService,
            IOrchardServices orchardServices)
        {
            _enumUrlSegmentService = enumUrlSegmentService;
            _orchardServices = orchardServices;

            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        public ActionResult Index()
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = new EnumUrlSegmentIndexViewModel()
            {
                Templates = _enumUrlSegmentService.GetList()
            };

            return View(viewModel);
        }

        public ActionResult Add()
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = new EnumUrlSegmentRecord();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(EnumUrlSegmentRecord viewModel)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _enumUrlSegmentService.Create(viewModel);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = _enumUrlSegmentService.Get(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(EnumUrlSegmentRecord viewModel)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var model = _enumUrlSegmentService.Get(viewModel.Id);
            if (TryUpdateModel(model))
            {
                _enumUrlSegmentService.Update(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(viewModel);
            }
        }

        public ActionResult Delete(int id)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = _enumUrlSegmentService.Get(id);
            _enumUrlSegmentService.Delete(viewModel);
            return RedirectToAction("Index");
        }

        bool IUpdateModel.TryUpdateModel<TModel>(TModel model, string prefix, string[] includeProperties, string[] excludeProperties)
        {
            return TryUpdateModel(model, prefix, includeProperties, excludeProperties);
        }

        void IUpdateModel.AddModelError(string key, LocalizedString errorMessage)
        {
            ModelState.AddModelError(key, errorMessage.Text);
        }
    }
}

Controllers/EnumUrlSegmentValueAdminController.cs
using MainBit.Alias.Helpers;
using MainBit.Alias.Models;
using MainBit.Alias.Services;
using MainBit.Alias.ViewModels;
using Orchard;
using Orchard.Caching;
using Orchard.Localization;
using Orchard.Security;
using Orchard.UI.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MainBit.Alias.Controllers
{
    [Admin]
    public class EnumUrlSegmentValueAdminController : Controller
    {
        private readonly IEnumUrlSegmentRepository _enumUrlSegmentRepository;
        private readonly IEnumUrlSegmentValueRepository _enumUrlSegmentValueRepository;
        private readonly IOrchardServices _orchardServices;

        public EnumUrlSegmentValueAdminController(
            IEnumUrlSegmentRepository enumUrlSegmentRepository,
            IEnumUrlSegmentValueRepository enumUrlSegmentValueRepository,
            IOrchardServices orchardServices)
        {
            _enumUrlSegmentRepository = enumUrlSegmentRepository;
            _enumUrlSegmentValueRepository = enumUrlSegmentValueRepository;
            _orchardServices = orchardServices;

            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        public ActionResult Index(int segmentId)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var segment = _enumUrlSegmentRepository.Get(segmentId);
            return View(segment);
        }

        public ActionResult Add(int segmentId)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = new EnumUrlSegmentValueRecord() {
                EnumUrlSegmentRecord_Id = segmentId
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(int segmentId, EnumUrlSegmentValueRecord viewModel)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var segment = _enumUrlSegmentRepository.Get(segmentId);
            viewModel.EnumUrlSegmentRecord_Id = segment.Id;
            segment.SegmentValues.Add(viewModel);

            return RedirectToAction("Index", new { segmentId = segmentId });
        }

        public ActionResult Edit(int id)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = _enumUrlSegmentValueRepository.Get(id);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(EnumUrlSegmentValueRecord viewModel)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _enumUrlSegmentValueRepository.Update(viewModel);

            return RedirectToAction("Index", new { segmentId = viewModel.EnumUrlSegmentRecord_Id });
        }

        public ActionResult Delete(int id)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage enum url segments")))
                return new HttpUnauthorizedResult();

            var viewModel = _enumUrlSegmentValueRepository.Get(id);
            _enumUrlSegmentValueRepository.Delete(viewModel);
            return RedirectToAction("Index", new { segmentId = viewModel.EnumUrlSegmentRecord_Id });
        }
    }
}

Views/EnumUrlSegmentAdmin/Add.cshtml
@model MainBit.Alias.Models.EnumUrlSegmentRecord
@{
    Layout.Title = T("Create enumeration URL segment");
}

@using (Html.BeginFormAntiForgeryPost()) {
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.Id)
    <fieldset>
        @Html.LabelFor(m => m.Position, T("Position"))
        @Html.TextBoxFor(m => m.Position, new { type = "number", @class = "text small" })
        @Html.ValidationMessageFor(m => m.Position)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.Name, T("Name"))
        @Html.TextBoxFor(m => m.Name, new { @class = "text medium" })
        @Html.ValidationMessageFor(m => m.Name)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.DisplayName, T("Display name"))
        @Html.TextBoxFor(m => m.DisplayName, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.DisplayName)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        <button class="primaryAction" type="submit">@T("Save")</button>
        @Html.ActionLink(T("Cancel").ToString(), "Index", new { }, new { @class = "button" })
    </fieldset>
}

Views/EnumUrlSegmentAdmin/Edit.cshtml
@model MainBit.Alias.Models.EnumUrlSegmentRecord
@{
    Layout.Title = T("Update enumeration URL segment");
}

@using (Html.BeginFormAntiForgeryPost())
{
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.Id)
    <fieldset>
        @Html.LabelFor(m => m.Position, T("Position"))
        @Html.TextBoxFor(m => m.Position, new { type = "number", @class = "text small" })
        @Html.ValidationMessageFor(m => m.Position)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.Name, T("Name"))
        @Html.TextBoxFor(m => m.Name, new { @class = "text medium" })
        @Html.ValidationMessageFor(m => m.Name)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.DisplayName, T("Display name"))
        @Html.TextBoxFor(m => m.DisplayName, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.DisplayName)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        <button class="primaryAction" type="submit">@T("Save")</button>
        @Html.ActionLink(T("Cancel").ToString(), "Index", new { }, new { @class = "button" })
    </fieldset>
}

Views/EnumUrlSegmentAdmin/Index.cshtml
@model MainBit.Alias.ViewModels.EnumUrlSegmentIndexViewModel
@{
    Layout.Title = T("Enumeration URL segments");
}
@Html.AntiForgeryTokenOrchard()
<div class="manage">
    @Html.ActionLink(T("Add").Text, "Add", new { Area = "MainBit.Alias" }, new { @class = "button primaryAction" })
</div>
<table class="items">
    <thead>
        <tr>
            <th scope="col">
                @T("Position")
            </th>
            <th scope="col">
                @T("Name")
            </th>
            <th>
                @T("Display name")
            </th>
            <th scope="col">
                @T("Actions")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var template in Model.Templates)
        {
            <tr>
                <td>
                    @template.Position
                </td>
                <td>
                    @template.Name
                </td>
                <td>
                    @template.DisplayName
                </td>
                <td>
                    @Html.ActionLink(T("Edit values").Text, "Index", "EnumUrlSegmentValueAdmin", new { segmentId = @template.Id, area = "MainBit.Alias" }, null)
                    @T(" | ")
                    @Html.ActionLink(T("Edit").Text, "Edit", "EnumUrlSegmentAdmin", new { id = @template.Id, area = "MainBit.Alias" }, null)
                    @T(" | ")
                    @Html.ActionLink(T("Delete").Text, "Delete", "EnumUrlSegmentAdmin", new { id = @template.Id, area = "MainBit.Alias" }, new { data_unsafe_url = T("Are you sure you want to delete this base url template?") })
                </td>
            </tr>
        }
    </tbody>
</table>