Controllers/UrlTemplateAdminController.cs
using MainBit.Alias.Models;
using MainBit.Alias.Services;
using MainBit.Alias.ViewModels;
using Orchard;
using Orchard.Caching;
using Orchard.Localization;
using Orchard.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MainBit.Alias.Helpers;
using Orchard.Themes;
using Orchard.UI.Admin;

namespace MainBit.Alias.Controllers
{
    [Admin]
    public class UrlTemplateAdminController : Controller
    {
        private readonly IUrlTemplateRepository _urlTemplateService;
        private readonly IOrchardServices _orchardServices;
        private readonly ISignals _signals;
        private readonly IUrlTemplateHelper _urlTemplateHelper;
        private readonly IUrlTemplateManager _urlTemplateManager;

        public UrlTemplateAdminController(
            IUrlTemplateRepository urlTemplateService,
            IOrchardServices orchardServices,
            ISignals signals,
            IUrlTemplateHelper urlTemplateHelper,
            IUrlTemplateManager urlTemplateManager)
        {
            _urlTemplateService = urlTemplateService;
            _orchardServices = orchardServices;
            _signals = signals;
            _urlTemplateHelper = urlTemplateHelper;
            _urlTemplateManager = urlTemplateManager;

            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        public ActionResult Index()
        {
            var viewModel = new UrlTemplateIndexViewModel()
            {
                Templates = _urlTemplateService.GetList(),
                Descriptors = _urlTemplateManager.DescribeUrlTemplates()

            };

            return View(viewModel);
        }

        public ActionResult Add()
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage url templates")))
                return new HttpUnauthorizedResult();

            var viewModel = new UrlTemplateRecord();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(UrlTemplateRecord viewModel)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage url templates")))
                return new HttpUnauthorizedResult();

            viewModel.BaseUrl = viewModel.BaseUrl.TrimSafe();
            viewModel.StoredPrefix = viewModel.StoredPrefix.TrimSafe();
            viewModel.Constraints = viewModel.Constraints.TrimSafe();

            if (String.IsNullOrWhiteSpace(viewModel.BaseUrl))
            {
                ModelState.AddModelError("BaseUrl", T("Base url can't be empty").Text);
            }

            try
            {
                var contraints = _urlTemplateHelper.ParseContraints(viewModel.Constraints);
            }
            catch
            {
                ModelState.AddModelError("Constraints", T("Constraints field is not valid.").Text);
            }

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _urlTemplateService.Create(viewModel);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage url templates")))
                return new HttpUnauthorizedResult();

            var viewModel = _urlTemplateService.Get(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(UrlTemplateRecord viewModel)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage url templates")))
                return new HttpUnauthorizedResult();

            viewModel.BaseUrl = viewModel.BaseUrl.TrimSafe();
            viewModel.StoredPrefix = viewModel.StoredPrefix.TrimSafe();
            viewModel.Constraints = viewModel.Constraints.TrimSafe();

            if (String.IsNullOrWhiteSpace(viewModel.BaseUrl))
            {
                ModelState.AddModelError("BaseUrl", T("Base url can't be empty").Text);
            }

            try
            {
                var contraints = _urlTemplateHelper.ParseContraints(viewModel.Constraints);
            }
            catch {
                ModelState.AddModelError("Constraints", T("Constraints field is not valid.").Text);
            }

            

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _urlTemplateService.Update(viewModel);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            if (!_orchardServices.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to manage url templates")))
                return new HttpUnauthorizedResult();

            var viewModel = _urlTemplateService.Get(id);
            _urlTemplateService.Delete(viewModel);
            return RedirectToAction("Index");
        }

        public ActionResult ClearСache()
        {
            _signals.Trigger(UrlTemplateManager.SignalUrlTemplatesChanged);
            return RedirectToAction("Index");
        }
    }
}

Views/UrlTemplateAdmin/Add.cshtml
@model MainBit.Alias.Models.UrlTemplateRecord
@{
    Layout.Title = T("Create URL template");
}

@using (Html.BeginFormAntiForgeryPost()) {
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.Id)
    <fieldset>
        @Html.LabelFor(m => m.Position, T("Position"))
        @Html.TextBoxFor(m => m.Position, new { type = "number", @class = "text small" })
        @Html.ValidationMessageFor(m => m.Position)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.BaseUrl, T("Base url"))
        @Html.TextBoxFor(m => m.BaseUrl, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.BaseUrl)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.StoredPrefix, T("Stored prefix"))
        @Html.TextBoxFor(m => m.StoredPrefix, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.StoredPrefix)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.Constraints, T("Constraints"))
        @Html.TextBoxFor(m => m.Constraints, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.Constraints)
        <span class="hint">@T("Regex constrains in json format, similar to MapRoute contraints. Example: {\"culture\"=\"^en-US$\",\"something\"=\"a|b\"}")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.IncludeDefaultValues, T("Include default vsalues"))
        @Html.CheckBoxFor(m => m.IncludeDefaultValues)
        @Html.ValidationMessageFor(m => m.IncludeDefaultValues)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        <button class="primaryAction" type="submit">@T("Save")</button>
        @Html.ActionLink(T("Cancel").ToString(), "Index", null, new { @class = "button" })
    </fieldset>
}

Views/UrlTemplateAdmin/Edit.cshtml
@model MainBit.Alias.Models.UrlTemplateRecord
@{
    Layout.Title = T("Update URL template");
}
@using (Html.BeginFormAntiForgeryPost())
{
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.Id)
    <fieldset>
        @Html.LabelFor(m => m.Position, T("Position"))
        @Html.TextBoxFor(m => m.Position, new { type = "number", @class = "text small" })
        @Html.ValidationMessageFor(m => m.Position)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.BaseUrl, T("Base url"))
        @Html.TextBoxFor(m => m.BaseUrl, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.BaseUrl)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.StoredPrefix, T("Stored prefix"))
        @Html.TextBoxFor(m => m.StoredPrefix, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.StoredPrefix)
        <span class="hint">@T("")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.Constraints, T("Constraints"))
        @Html.TextBoxFor(m => m.Constraints, new { @class = "text large" })
        @Html.ValidationMessageFor(m => m.Constraints)
        <span class="hint">@T("Regex constrains in json format, similar to MapRoute contraints. Example: {\"culture\"=\"^en-US$\",\"something\"=\"a|b\"}")</span>
    </fieldset>
    <fieldset>
        @Html.LabelFor(m => m.IncludeDefaultValues, T("Include default vsalues"))
        @Html.CheckBoxFor(m => m.IncludeDefaultValues)
        @Html.ValidationMessageFor(m => m.IncludeDefaultValues)
        <span class="hint">@T("")</span>
    </fieldset>

    
    <fieldset>
        <button class="primaryAction" type="submit">@T("Save")</button>
        @Html.ActionLink(T("Cancel").ToString(), "Index", null, new { @class = "button" })
    </fieldset>
}

Views/UrlTemplateAdmin/Index.cshtml
@model MainBit.Alias.ViewModels.UrlTemplateIndexViewModel
@{
    Layout.Title = T("URL templates");
}
@Html.AntiForgeryTokenOrchard()
<div class="manage">
    @Html.ActionLink(T("Clear сache").Text, "ClearСache", new { Area = "MainBit.Alias" }, new { @class = "button primaryAction" })
    @Html.ActionLink(T("Add").Text, "Add", new { Area = "MainBit.Alias" }, new { @class = "button primaryAction" })
</div>
<table class="items">
    <thead>
        <tr>
            <th scope="col">
                @T("Position")
            </th>
            <th scope="col">
                @T("Base URL")
            </th>
            <th>
                @T("Stored prefix")
            </th>
            <th>
                @T("Constraints")
            </th>
            <th>
                @T("Include default values")
            </th>
            <th scope="col">
                @T("Actions")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var template in Model.Templates)
        {
            <tr>
                <td>
                    @template.Position
                </td>
                <td>
                    @template.BaseUrl
                </td>
                <td>
                    @template.StoredPrefix
                </td>
                <td>
                    @template.Constraints
                </td>
                <td>
                    @template.IncludeDefaultValues
                </td>
                <td>
                    @Html.ActionLink(T("Edit").Text, "Edit", "UrlTemplateAdmin", new { id = @template.Id, area = "MainBit.Alias" }, null)
                    @T(" | ")
                    @Html.ActionLink(T("Delete").Text, "Delete", "UrlTemplateAdmin", new { id = @template.Id, area = "MainBit.Alias" }, new { data_unsafe_url = T("Are you sure you want to delete this base url template?") })
                </td>
            </tr>
        }
    </tbody>
</table>


<h3 style="margin-top: 5rem;">@T("Result URLs (cached)")</h3>
<table class="items">
    <thead>
        <tr>
            <td>@T("Base url")</td>
            <td>@T("Stored prefix")</td>
        </tr>
    </thead>
    <tbody>
    @foreach (var descriptor in Model.Descriptors)
    {
        <tr>
            <td>@descriptor.BaseUrl</td>
            <td>@descriptor.StoredPrefix</td>
        </tr>
    }
    </tbody>
</table>